### ISSUE TITLE
Problem closing the trade

### ISSUE THREAD

**Issue by bgsaie** [AlleSchonWeg/eToroCloseCryptos#5]
Hi! First off, great script! Unfortunately it seems to have trouble closing the trade. I've tried it on my virtual account as well - the "close trade" box opens, but it doesn't close the trade. I have tried the script in Firefox and Chrome, and I have followed your instructions. Could you look into it?

Thanks in advance!

**Comment by AlleSchonWeg** [comment]
Hi,
i  changed the timeout. Now it should work again. Version 1.4. Tested in chrome.

**Comment by bgsaie** [comment]
Works like a dream, thank you :) 

Just curious: What is the copy/paste script? I'm already able to copy/paste text. Are you talking about copying trades or something in that regard?

**Comment by bgsaie** [comment]
Would it be possible to improve the script so it works while switching tabs?

**Comment by AlleSchonWeg** [comment]
Hi,
it should work, but i don't know why it's not working. 
But, as a workaround, you can open a second chrome instance with one etoro tab.

**Comment by bgsaie** [comment]
Thanks for the idea. Would it be possible to make it work in offline mode, so I don't have to keep my computer on at night?

**Comment by bgsaie** [comment]
Thanks. Would it be possible to make it work in offline mode, so I don't have to keep my computer on at night?

**Comment by AlleSchonWeg** [comment]
No. You the computer needs to be on. Because it's off no data is send from etoro and the script cannot be run if the computer is off.
